#!/bin/bash

if [ -z "$1" ]; then
  environment="dev"
else
  environment="$1"
fi

case "$environment" in
  dev)
    echo "Cleaning development environment..."
    docker-compose -f docker-compose.dev.yml down -v --rmi all
    ;;
  prod)
    echo "Cleaning production environment..."
    docker-compose -f docker-compose.prod.yml down -v --rmi all
    ;;
  all)
    echo "Cleaning development y production environments..."
    docker-compose -f docker-compose.dev.yml down -v --rmi all
    docker-compose -f docker-compose.prod.yml down -v --rmi all
    ;;
  *)
    echo "Use: $0 {dev|prod|all}"
    exit 1
    ;;
esac