services:
  backend:
    image: node:22
    container_name: time-trackr-backend
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend
    working_dir: /app/backend
    entrypoint: ["/bin/bash", "-c", "npm install && npm run start:dev"]
    ports:
      - "3000:3000"
    networks:
      - time-trackr-network
    environment:
      - NODE_ENV=development
    depends_on:
      - db
      - redis

  frontend:
    image: node:22
    container_name: time-trackr-frontend
    volumes:
      - ./frontend:/app/frontend
    working_dir: /app/frontend
    entrypoint: ["/bin/bash", "-c", "npm install && npm run serve"]
    ports:
      - "5173:5173"
    networks:
      - time-trackr-network
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  db:
    image: postgres:17.4
    container_name: time-trackr-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - time-trackr-network

  redis:
    image: redis:latest
    container_name: time-trackr-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - time-trackr-network

networks:
  time-trackr-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: