services:
  backend:
    image: node:lts
    container_name: time-trackr-backend
    volumes:
      - ./backend:/app/backend
    working_dir: /app/backend
    entrypoint: ["/bin/bash", "-c", "npm install && npm run start:dev"]
    ports:
      - "3000:3000"
    networks:
      - time-trackr-network
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  frontend:
    image: node:lts
    container_name: time-trackr-frontend
    volumes:
      - ./frontend:/app/frontend
    working_dir: /app/frontend
    entrypoint: ["/bin/bash", "-c", "npm install && npm run serve"]
    ports:
      - "8080:8080"
    networks:
      - time-trackr-network
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  db:
    image: postgres:17.4
    container_name: time-trackr-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: time-trackr
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - time-trackr-network

networks:
  time-trackr-network:
    driver: bridge

volumes:
  postgres_data: