#!/bin/bash

if [ -z "$1" ]; then
  environment="dev"
else
  environment="$1"
fi

echo "Initializing and updating submodules..."
git submodule init
git submodule update --recursive

case "$environment" in
  dev)

    echo "Copying .env to frontend and backend..."
    cp ./.env.dev ./frontend/.env.dev
    cp ./.env.dev ./backend/.env.dev

    echo "Starting development environment..."
    docker-compose -f docker-compose.dev.yml up
    ;;
  prod)
    echo "Pulling latest changes..."
    git pull --recurse-submodules

    if [ ! -f "./.env.prod" ]; then
      echo "Error: .env.prod not found."
      exit 1
    fi

    echo "Copying .env.prod to frontend and backend..."
    cp ./.env.prod ./frontend/.env.prod
    cp ./.env.prod ./backend/.env.prod

    echo "Cleaning prod environment..."
    ./clean prod

    echo "Starting production environment..."
    docker-compose -f docker-compose.prod.yml up --build -d
    ;;
  *)
    echo "Use: $0 {dev|prod}"
    exit 1
    ;;
esac