#!/bin/bash

if [ -z "$1" ]; then
  environment="dev"
else
  environment="$1"
fi

case "$environment" in
  dev)
    echo "Starting development environment..."
    docker-compose -f docker-compose.dev.yml up
    ;;
  prod)
    echo "Starting production environment..."
    docker-compose -f docker-compose.prod.yml up --build -d
    ;;
  *)
    echo "Use: $0 {dev|prod}"
    exit 1
    ;;
esac