name: Deploy to production

on:
  push: {}
  repository_dispatch:
    types: [trigger-deploy]
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      app_token: ${{ steps.generate-token.outputs.token }}
    steps:
      - name: Generate App Token
        id: generate-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          installation_id: ${{ secrets.APP_INSTALLATION_ID }}
          revoke: false

      - name: Debug - Token generado
        run: echo "Token: ${{ steps.generate-token.outputs.token }}"

  deploy:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs:
            GITHUB_TOKEN: ${{ needs.prepare.outputs.app_token }}
          script: |
            set -ex
            PROJECT_DIR="/root/projects/timeTrackrProd"

            cp "$PROJECT_DIR/.env.prod" /tmp/.env.prod.backup

            cd "$PROJECT_DIR"
            git config --global url."https://x-access-token:$GITHUB_TOKEN@github.com".insteadOf "https://github.com"
            git pull origin main
            git submodule sync
            git submodule update --init --remote --force

            mv "/tmp/.env.prod.backup" "$PROJECT_DIR/.env.prod"

            cd "$PROJECT_DIR"
            chmod +x ./start
            ./start prod