name: Deploy to production

on:
  push: {}
  repository_dispatch:
    types: [trigger-deploy]
  workflow_dispatch:

jobs:
  deploy:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -ex
            PROJECT_DIR="/root/projects/timeTrackrProd"

            cd "$PROJECT_DIR"
            git pull

            ./start prod